name: qr_scanner_app
description: Ứng dụng quét QR và lưu lịch sử
publish_to: 'none'
version: 1.0.6+8
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  qr_code_scanner: ^1.0.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  flutter_inappwebview: ^6.0.0
  http: ^1.4.0
  qr_flutter: ^4.1.0
  permission_handler: ^11.3.1
  geolocator: ^10.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "favicon_io/android-chrome-512x512.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "favicon_io/android-chrome-512x512.png"
  remove_alpha_ios: true