name: qr_scanner_app
description: Ứng dụng quét QR và lưu lịch sử
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  qr_code_scanner: ^1.0.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true